# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: postgres-pv-volume
#   namespace: imi-sophia
# spec:
#   # storageClassName: manual
#   capacity:
#     storage: 10Gi
#   accessModes:
#     - ReadWriteOnce
#   # hostPath:
#   #   path: "/mnt/data"
# ---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv-claim
  namespace: r-daises
spec:
  # storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vantage6-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      serviceAccountName: anyuid
      containers:
        - name: vantage6-postgres
          image: postgres:12.4
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres"
            - name: POSTGRES_DB
              value: "vantage6"
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql
            - name: dshm
              mountPath: /dev/shm
          ports:
            - containerPort: 5432
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-pv-claim
---
kind: Service
apiVersion: v1
metadata:
  name: postgres-service
spec:
  selector:
    app: postgres
  type: LoadBalancer
  ports:
    - port: 5432
      targetPort: 5432
      name: postgres-api